-- MySQL Script generated by MySQL Workbench
-- 10/30/15 15:01:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SoccerUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SoccerUser` (
  `idSoccerUser` INT NOT NULL AUTO_INCREMENT COMMENT 'id del usuario a nivel de sistema',
  `username` VARCHAR(45) NOT NULL COMMENT 'nombre de usuario',
  `soccerPassword` VARCHAR(45) NOT NULL COMMENT 'contraseña de usuario',
  `idEmployee` INT NOT NULL COMMENT 'id del empleado que creo el usuario',
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idSoccerUser`),
  UNIQUE INDEX `soccerPassword_UNIQUE` (`soccerPassword` ASC),
  UNIQUE INDEX `idEmployee_UNIQUE` (`idEmployee` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParameterTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParameterTable` (
  `nameTag` VARCHAR(45) NOT NULL COMMENT 'Tag para identificar la tupla',
  `valueParameter` INT NOT NULL COMMENT 'Parametro que se usa en el sistema',
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`nameTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT COMMENT 'id de la persona a nivel de base',
  `dni` INT NOT NULL COMMENT 'identificacion de la persona',
  `birthdate` DATE NOT NULL COMMENT 'fecha de nacimiento',
  `firstName` VARCHAR(45) NOT NULL,
  `secondName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Continent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Continent` (
  `idContinent` INT NOT NULL AUTO_INCREMENT,
  `nameContinent` VARCHAR(45) NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idContinent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `idCountry` INT NOT NULL AUTO_INCREMENT,
  `nameCountry` VARCHAR(45) NOT NULL,
  `flag` VARCHAR(45) NOT NULL,
  `idContinent` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idCountry`),
  INDEX `fk_country_idContinent_idx` (`idContinent` ASC),
  CONSTRAINT `fk_country_idContinent`
    FOREIGN KEY (`idContinent`)
    REFERENCES `mydb`.`Continent` (`idContinent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `idPlayer` INT NOT NULL AUTO_INCREMENT,
  `height` VARCHAR(45) NOT NULL,
  `weight` VARCHAR(45) NOT NULL,
  `shirtNum` INT NOT NULL,
  `idPerson` INT NOT NULL,
  `idCountry` INT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idPlayer`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC),
  INDEX `fk_Player_idCountry_idx` (`idCountry` ASC),
  CONSTRAINT `fk_Player_idPerson`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_idCountry`
    FOREIGN KEY (`idCountry`)
    REFERENCES `mydb`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coach` (
  `idCoach` INT NOT NULL AUTO_INCREMENT,
  `idPerson` INT NOT NULL,
  `idCountry` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idCoach`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC),
  INDEX `fk_coach_idCountry_idx` (`idCountry` ASC),
  CONSTRAINT `fk_coach_idperson`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coach_idCountry`
    FOREIGN KEY (`idCountry`)
    REFERENCES `mydb`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `nameCity` VARCHAR(45) NOT NULL,
  `idCountry` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idCity`),
  INDEX `fk_city_idCountry_idx` (`idCountry` ASC),
  CONSTRAINT `fk_city_idCountry`
    FOREIGN KEY (`idCountry`)
    REFERENCES `mydb`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EventStructure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EventStructure` (
  `idEventStructure` INT NOT NULL AUTO_INCREMENT,
  `quantityTeam` INT NOT NULL,
  `quantityGroup` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idEventStructure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `nameEvent` VARCHAR(45) NOT NULL,
  `dateStartEvent` DATE NOT NULL,
  `dateEndEvent` DATE NOT NULL,
  `idEventStructure` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idEvent`),
  INDEX `fk_Event_idEventStructure_idx` (`idEventStructure` ASC),
  CONSTRAINT `fk_Event_idEventStructure`
    FOREIGN KEY (`idEventStructure`)
    REFERENCES `mydb`.`EventStructure` (`idEventStructure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `idGroup` INT NOT NULL AUTO_INCREMENT,
  `nameGroup` VARCHAR(45) NOT NULL,
  `idEvent` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idGroup`),
  INDEX `fk_Group_idEvent_idx` (`idEvent` ASC),
  CONSTRAINT `fk_Group_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Team` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `nameTeam` VARCHAR(45) NOT NULL,
  `captain` VARCHAR(45) NOT NULL,
  `idCountry` INT NOT NULL,
  `idGroup` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idTeam`),
  INDEX `fk_Team_idCountry_idx` (`idCountry` ASC),
  INDEX `fk_Team_idGroup_idx` (`idGroup` ASC),
  CONSTRAINT `fk_Team_idCountry`
    FOREIGN KEY (`idCountry`)
    REFERENCES `mydb`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_idGroup`
    FOREIGN KEY (`idGroup`)
    REFERENCES `mydb`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AwardTeam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AwardTeam` (
  `idAwardTeam` INT NOT NULL AUTO_INCREMENT,
  `nameAward` VARCHAR(45) NOT NULL,
  `dateAward` DATE NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  `idTeam` INT NOT NULL,
  PRIMARY KEY (`idAwardTeam`),
  INDEX `fk_AwardTeam_idTeam_idx` (`idTeam` ASC),
  CONSTRAINT `fk_AwardTeam_idTeam`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `idHome` INT NOT NULL,
  `idVisitor` INT NOT NULL,
  `matchJourney` INT NOT NULL,
  `dateTimeGame` DATETIME NOT NULL,
  `totalGameTime` INT NOT NULL,
  `idEvent` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idGame`),
  INDEX `fk_Game_idEvent_idx` (`idEvent` ASC),
  CONSTRAINT `fk_Game_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Penalty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Penalty` (
  `idPenalty` INT NOT NULL AUTO_INCREMENT,
  `idShooter` INT NOT NULL,
  `idGoalie` INT NOT NULL,
  `score` TINYINT(1) NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idPenalty`),
  INDEX `fk_Penalty_idGame_idx` (`idGame` ASC),
  CONSTRAINT `fk_Penalty_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stadium` (
  `idStadium` INT NOT NULL AUTO_INCREMENT,
  `nameStadium` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `idCity` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idStadium`),
  INDEX `fk_Stadium_idCity_idx` (`idCity` ASC),
  CONSTRAINT `fk_Stadium_idCity`
    FOREIGN KEY (`idCity`)
    REFERENCES `mydb`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Goal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Goal` (
  `idGoal` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `minute` INT NOT NULL,
  `isPenalty` TINYINT(1) NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idGoal`),
  INDEX `fk_Goal_idGame_idx` (`idGame` ASC),
  INDEX `fk_Goal_idPlayer_idx` (`idPlayer` ASC),
  CONSTRAINT `fk_Goal_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Goal_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offside`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Offside` (
  `idOffside` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` INT NULL,
  PRIMARY KEY (`idOffside`),
  INDEX `fk_Offside_idGame_idx` (`idGame` ASC),
  INDEX `fk_Offside_idPlayer_idx` (`idPlayer` ASC),
  CONSTRAINT `fk_Offside_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offside_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BallPossesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BallPossesion` (
  `idBallPossesion` INT NOT NULL AUTO_INCREMENT,
  `porcentage` DOUBLE NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idBallPossesion`),
  INDEX `fk_BallPossesion_idGame_idx` (`idGame` ASC),
  CONSTRAINT `fk_BallPossesion_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LineUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LineUp` (
  `idLineUp` INT NOT NULL AUTO_INCREMENT,
  `idTeam` INT NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idLineUp`),
  INDEX `fk_LineUp_idTeam_idx` (`idTeam` ASC),
  INDEX `fk_LineUp_idGame_idx` (`idGame` ASC),
  CONSTRAINT `fk_LineUp_idTeam`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LineUp_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SustitutionLineUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SustitutionLineUp` (
  `idSustitutionLineUp` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `idPlayerReplacement` INT NULL,
  `minute` INT NOT NULL,
  `idLineUp` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idSustitutionLineUp`),
  INDEX `fk_Sustitution_idplayer_idx` (`idPlayer` ASC),
  INDEX `fk_Sustitution_idPlayerReplace_idx` (`idPlayerReplacement` ASC),
  INDEX `fkSustitution_idLineUp_idx` (`idLineUp` ASC),
  CONSTRAINT `fk_Sustitution_idplayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sustitution_idPlayerReplace`
    FOREIGN KEY (`idPlayerReplacement`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkSustitution_idLineUp`
    FOREIGN KEY (`idLineUp`)
    REFERENCES `mydb`.`LineUp` (`idLineUp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Position` (
  `idPosition` INT NOT NULL AUTO_INCREMENT,
  `namePoistion` VARCHAR(45) NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idPosition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player_LineUp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player_LineUp` (
  `idPlayer_LineUp` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `idLineUp` INT NOT NULL,
  `idPosition` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idPlayer_LineUp`),
  INDEX `fk_idPosition_idx` (`idPosition` ASC),
  CONSTRAINT `fk_idPosition`
    FOREIGN KEY (`idPosition`)
    REFERENCES `mydb`.`Position` (`idPosition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player_team` (
  `idPlayer_team` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `idTeam` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idPlayer_team`),
  INDEX `fk_player_team_idPlayer_idx` (`idPlayer` ASC),
  INDEX `fk_player_team_idTeam_idx` (`idTeam` ASC),
  CONSTRAINT `fk_player_team_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_team_idTeam`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stadium_Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stadium_Game` (
  `idStadium_Game` INT NOT NULL AUTO_INCREMENT,
  `idStadium` INT NOT NULL,
  `idGame` INT NOT NULL,
  `idCity` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idStadium_Game`),
  INDEX `fk_Stadium_Game_idStadium_idx` (`idStadium` ASC),
  INDEX `fk_Stadium_Game_idGame_idx` (`idGame` ASC),
  CONSTRAINT `fk_Stadium_Game_idStadium`
    FOREIGN KEY (`idStadium`)
    REFERENCES `mydb`.`Stadium` (`idStadium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stadium_Game_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AwardPerson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AwardPerson` (
  `idAwardPerson` INT NOT NULL AUTO_INCREMENT,
  `nameAwardPerson` VARCHAR(45) NOT NULL,
  `dateAward` DATE NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  `idPlayer` INT NOT NULL,
  PRIMARY KEY (`idAwardPerson`),
  INDEX `fk_AwardPerson_idPlayer_idx` (`idPlayer` ASC),
  CONSTRAINT `fk_AwardPerson_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Save`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Save` (
  `idSave` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idSave`),
  INDEX `fk_Save_idPlater_idx` (`idPlayer` ASC),
  INDEX `fk_Save_idGame_idx` (`idGame` ASC),
  CONSTRAINT `fk_Save_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Save_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Foul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Foul` (
  `idFoul` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idFoul`),
  INDEX `fk_Faul_idPlayer_idx` (`idPlayer` ASC),
  INDEX `fk_Faul_idGame_idx` (`idGame` ASC),
  CONSTRAINT `fk_Foul_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Foul_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Card` (
  `idCard` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `color` TINYINT(1) NOT NULL,
  `minute` INT NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idCard`),
  INDEX `fk_Card_idPlayer_idx` (`idGame` ASC),
  CONSTRAINT `fk_Card_idPlayer`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AttemptType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AttemptType` (
  `idAttemptType` INT NOT NULL AUTO_INCREMENT,
  `nameAttemptType` VARCHAR(45) NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idAttemptType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attempt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attempt` (
  `idAttempt` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  `idAttemptType` INT NOT NULL,
  PRIMARY KEY (`idAttempt`),
  INDEX `fk_Attempt_AttemptType_idx` (`idAttemptType` ASC),
  INDEX `fk_Attempt_idPlayer_idx` (`idPlayer` ASC),
  INDEX `fk_Attempt_idGame_idx` (`idGame` ASC),
  CONSTRAINT `fk_Attempt_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attempt_idAttemptType`
    FOREIGN KEY (`idAttemptType`)
    REFERENCES `mydb`.`AttemptType` (`idAttemptType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attempt_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Corner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Corner` (
  `idCorner` INT NOT NULL AUTO_INCREMENT,
  `idPlayer` INT NOT NULL,
  `idGame` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idCorner`),
  INDEX `fk_Corner_idPlayer_idx` (`idPlayer` ASC),
  INDEX `fk_Corner_idGame_idx` (`idGame` ASC),
  CONSTRAINT `fk_Corner_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Corner_idGame`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `mydb`.`Award_Player` (
  `idAward_Player` INT NOT NULL AUTO_INCREMENT,
  `idAwardPerson` INT NOT NULL,
  `idPlayer` INT NOT NULL,
  `idEvent` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idAward_Player`),
  UNIQUE INDEX `idPlayer_UNIQUE` (`idPlayer` ASC),
  UNIQUE INDEX `idAwardPerson_UNIQUE` (`idAwardPerson` ASC),
  UNIQUE INDEX `idEvent_UNIQUE` (`idEvent` ASC),
  CONSTRAINT `fk_Award_Player_idPlayer`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Award_Player_idAwardPerson`
    FOREIGN KEY (`idAwardPerson`)
    REFERENCES `mydb`.`AwardPerson` (`idAwardPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Award_Player_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

drop table Award_Team;
CREATE TABLE IF NOT EXISTS `mydb`.`Award_Team` (
  `idAward_Team` INT NOT NULL AUTO_INCREMENT,
  `idAwardTeam` INT NOT NULL,
  `idTeam` INT NOT NULL,
  `idEvent` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idAward_Team`),
  UNIQUE INDEX `idAwardTeam_UNIQUE` (`idAwardTeam` ASC),
  UNIQUE INDEX `idTeam_UNIQUE` (`idTeam` ASC),
  UNIQUE INDEX `idEvent_UNIQUE` (`idEvent` ASC),
  CONSTRAINT `fk_Award_Team_idTeam`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Award_Team_idAwardTeam`
    FOREIGN KEY (`idAwardTeam`)
    REFERENCES `mydb`.`AwardTeam` (`idAwardTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Award_Team_idEvent`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

drop table ParameterTableGroup;
CREATE TABLE IF NOT EXISTS `mydb`.`ParameterTableGroup` (
  `numberTag` INT NOT NULL,
  `nameGroup` VARCHAR(45) NOT NULL COMMENT 'Campo para los nombres de cada grupo. Se usan cuando se crean nuevos grupos durantes los eventos.',
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`numberTag`),
  UNIQUE INDEX `nameGroup_UNIQUE` (`nameGroup` ASC))
ENGINE = InnoDB;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


CREATE TABLE IF NOT EXISTS `mydb`.`Dashboard` (
  `idDashboard` INT NOT NULL AUTO_INCREMENT,
  `goalsPerMatch` INT NOT NULL,
  `expulsions` INT NOT NULL,
  `cautions` INT NOT NULL,
  `avergeShotsPerTeam` INT NOT NULL,
  `avergeMinutesPerMatch` INT NOT NULL,
  `matchesPlayed` INT NOT NULL,
  `createdBy` VARCHAR(45) NULL,
  `createdOn` DATE NULL,
  `updatedBy` VARCHAR(45) NULL,
  `updatedOn` DATE NULL,
  PRIMARY KEY (`idDashboard`))
ENGINE = InnoDB